[ERROR] File already exists: /raid/local/containers/enroot-data/user-1787/pytorch
Sliding Window Attention is enabled but not implemented for `sdpa`; unexpected results may be encountered.
Loading checkpoint shards:   0%|          | 0/17 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/projects/fraudagent/hase-michael/V3/eval.py", line 74, in <module>
    main()
  File "/home/projects/fraudagent/hase-michael/V3/eval.py", line 27, in main
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 279, in _wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 4399, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 4793, in _load_pretrained_model
    caching_allocator_warmup(model_to_load, expanded_device_map, factor=2 if hf_quantizer is None else 4)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 5799, in caching_allocator_warmup
    device_memory = torch.cuda.mem_get_info(index)[0]
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/memory.py", line 702, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Loading checkpoint shards:   0%|          | 0/17 [00:00<?, ?it/s]
